default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.dig(:database,:username) %>
  password: <%= Rails.application.credentials.dig(:database,:password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: solos_development

test:
  <<: *default
  database: solos_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database,:postgres_db) %>
